### ISSUE TITLE
scippneutron.convert, mantid.simpleapi.ConvertUnits differences

### ISSUE THREAD

**Issue by OwenArnold** [scipp/scippneutron#27]
See https://github.com/scipp/scippneutron/pull/16#discussion_r587222620

Going to tighter tolerances causes test failure where we cross-compare coordinates. We need to understand the origin of these differences. Easy to reproduce simply by changing the tolerance factor in the line linked above.

**Comment by jl-wynen** [comment]
I cannot reproduce the failure related to the line linked here.
However, reducing the tolerance in https://github.com/scipp/scippneutron/blob/690d17ba9c914a5ce87d5d4fd6ecd411ec5b0844/tests/mantid_scipp_comparison/test_neutron_convert_units.py#L123 does make the test fail.

Instead of finding the differences between scipp and mantid with the current test setup, I would rather refactor and simplify the tests. I find it hard to reason about them given the nested fixtures and especially the `allow_failure` flag.
